# Generated by Django 5.2.17 on 2026-09-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_booking_bookingseat_movie_paymenttransaction_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='seat_ids',
            field=models.JSONField(default=list),
        ),
    ]
